#!/bin/sh

set -e

neoziv_LIB_DIR=/var/lib/neoziv
neoziv_USER="neoziv"
neoziv_GROUP="neoziv"

case "${1}" in
    remove)
        deluser --quiet --system $neoziv_USER || true
        delgroup --quiet --system --only-if-empty $neoziv_GROUP || true
        ;;

    purge)
        if [ -d "$neoziv_LIB_DIR" ]; then
            rm -rf $neoziv_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
