#!/bin/sh

set -e

neoziv_CONFIGURATION_FILE=/etc/neoziv/neoziv.conf
neoziv_GROUP="neoziv"
neoziv_DATA_DIR=/var/lib/neoziv
neoziv_LOG_DIR=/var/log/neoziv
neoziv_USER="neoziv"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^neoziv:"; then
            adduser --system --home $neoziv_DATA_DIR --quiet --group $neoziv_USER
        fi
        # Register "$neoziv_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $neoziv_USER" 2> /dev/null || true
        # Configuration file
        chown $neoziv_USER:$neoziv_GROUP $neoziv_CONFIGURATION_FILE
        chmod 0640 $neoziv_CONFIGURATION_FILE
        # Log
        mkdir -p $neoziv_LOG_DIR
        chown $neoziv_USER:$neoziv_GROUP $neoziv_LOG_DIR
        chmod 0750 $neoziv_LOG_DIR
        # Data dir
        chown $neoziv_USER:$neoziv_GROUP $neoziv_DATA_DIR
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
